"""Audited XML schemas and shop identifiers, not executable import profiles."""

FORMATS = {
    "anthemidis": dict(hosts={"www.anthemidis.gr", "anthemidis.gr"}, root="channel", path=("channel", "item"),
        code="product_sku", sku="product_sku", name="product_name", category="category_path",
        stock="product_in_stock", description="product_desc", image="picture_url", ean="product_gtin",
        retail="Web_price", prefix="", step="min_order_level"),
    "arlight": dict(hosts={"arlight.gr", "www.arlight.gr"}, root="data", path=("data", "post"),
        code="Sku", sku="Sku", name="Title", category="Κατηγορίεςπροϊόντος",
        stock="Stock", description="Content", image="ImageURL", ean=None,
        retail="retail-price-with-vat", prefix=""),
    "buyway": dict(hosts={"buyway.gr", "www.buyway.gr"}, root="Store", path=("Store", "Products", "Product"),
        code="SKU", sku="SKU", name="Name", category="Category", stock=None,
        description="Description", image="Picture1", ean="Barcode", retail="RetailPrice", prefix="BW."),
    "daisat": dict(hosts={"www.daisat.gr", "daisat.gr"}, root="STOREITEMS", path=("STOREITEMS", "PRODUCT"),
        code="sku", sku="sku", name="NAME", category="category_name", stock="QUANTITY",
        description="description", image="IMAGE_URL", ean="ean", retail=None, prefix="dai.",
        wholesale="price_wholesale_untaxed"),
    "getters": dict(hosts={"admin.getters.gr"}, root="STOREITEMS", path=("STOREITEMS", "products", "product"),
        code="sku", sku="sku", name="name", category="category", stock="quantity",
        description="description", image="image", ean="ean", retail="price", prefix="g."),
    "gloria": dict(hosts={"www.gloria.gr", "gloria.gr"}, root="store", path=("store", "products", "product"),
        code="code", sku="code", name="name", category="category", stock="availability",
        description="description", image="image", ean="ean", retail="priceSuggested", prefix="GL.", model="@id"),
    "kanellopoulos": dict(hosts={"kanellopoulos-co.gr", "www.kanellopoulos-co.gr"}, root="itemlist", path=("itemlist", "item"),
        code="SKU", sku="SKU", name="Name_el", category="Category", stock="Quantity",
        description="Description_el", image="Image", ean="EAN", retail="LIANIKH", prefix="", step="minimum_quantity"),
    "printezis": dict(hosts={"printezis.com", "www.printezis.com"}, root="products", path=("products", "product"),
        code="sku", sku="sku", name="title", category="categories", stock=None,
        description=None, image="image_url", ean=None, retail="reg_price", prefix="pa."),
    "mastershop": dict(hosts={"www.mastershop.gr", "mastershop.gr"}, root="products", path=("products", "product"),
        code="reference", sku="reference", name="name", category="product_category_tree", stock="quantity",
        description="description", image="image", ean=None, retail=None, prefix=""),
    "spm": dict(hosts={"api.spm-network.com"}, root="spm", path=("spm", "products", "product"),
        code="sku", sku="sku", name="title", category="category", stock="amount",
        description="full_description", image="main_image", ean="barcode", retail=None, prefix="sp."),
}

# Deliberate allowlist: personal/author metadata and arbitrary URLs are not retained.
SOURCE_FIELDS = {
    "anthemidis": ("pricewithouttax", "Web_price", "neth-price", "product_available_date", "published",
        "product_height", "product_length", "product_width", "product_weight", "product_box", "kyv_ana_tem", "min_order_level"),
    "arlight": ("ID", "Price", "RegularPrice", "SalePrice", "StockStatus", "Status", "TaxStatus", "TaxClass",
        "Length", "Width", "Height", "Weight", "AttributeValuepa_diastaseis", "AttributeValuepa_ogkos", "retail-price-final"),
    "buyway": ("ProductId", "InStock", "ProductAvailability", "RecyclingCost", "Weight", "Length", "Width", "Height"),
    "daisat": ("id", "MODEL", "mpn", "price_retail_untaxed", "WEIGHT", "packaging_boxes", "packaging_info", "InStock", "Availability"),
    "getters": ("id", "list_price", "Vat", "mpn", "weight", "instock", "availability", "manufacturer"),
    "gloria": ("priceWholesale", "expected", "status", "weight", "mass", "dimension_x", "dimension_y", "dimension_z"),
    "kanellopoulos": ("Model", "Price", "WEBPRICE", "WEBPRICE_OFFER", "Status", "Weight", "Length", "Width", "Height", "minimum_quantity"),
    "printezis": ("sale_price", "discount_percentage", "availability", "dimensions", "colors", "material"),
    "mastershop": ("product_id", "price", "ean13", "height", "width", "depth", "weight"),
    "spm": ("product_id", "xondriki", "lianiki", "arxiki_timi", "price_no_fpa", "discount", "weight", "availability"),
}
